#!/usr/bin/env python
SERVER_IP = '10.128.100.9'
SERVER_PORT = '8080'
USER = 'padmin@vicci.org'
PASSWD = 'letmein'
TENANT_SUBSCRIBER = '/api/tenant/cord/subscriber/'
TENANT_VOLT = '/api/tenant/cord/volt/'
UTILS_SYNCHRONIZER = '/api/utility/synchronizer/'
UTILS_LOGIN = '/api/utility/login/'
CORE_USERS = '/api/core/users/'
CORE_SERVICES = '/api/core/services/'
CORE_INSTANCES = '/api/core/instances/'
CORE_DEPLOYMENTS = '/api/core/deployments/'
