FROM ubuntu:14.04
MAINTAINER chgaonke@partner.ciena.com

RUN apt-get update && \
    apt-get install -qy vlan python python-pexpect strace \
    python python-pip python-setuptools python-scapy tcpdump doxygen doxypy wget \
    openvswitch-common openvswitch-switch \
    python-twisted python-sqlite sqlite3 python-pexpect telnet arping isc-dhcp-server \
    python-paramiko python-maas-client

