
# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


FROM xosproject/xos-base

ARG XOS_GIT_COMMIT_HASH=unknown
ARG XOS_GIT_COMMIT_DATE=unknown

LABEL XOS_GIT_COMMIT_HASH=$XOS_GIT_COMMIT_HASH
LABEL XOS_GIT_COMMIT_DATE=$XOS_GIT_COMMIT_DATE

# Include certificates from Openstack
ADD containers/xos/local_certs.crt /usr/local/share/ca-certificates/local_certs.crt
RUN update-ca-certificates

# Install XOS
ADD xos /opt/xos

# ng-xos-lib download
ENV NG_XOS_LIB_URL https://github.com/opencord/ng-xos-lib.git
ENV NG_XOS_LIB_VERSION 1.0.0

RUN git clone $NG_XOS_LIB_URL /tmp/ng-xos-lib \
 && cd /tmp/ng-xos-lib  \
 && git checkout tags/$NG_XOS_LIB_VERSION \
 && cp /tmp/ng-xos-lib/dist/ngXosHelpers.min.js /opt/xos/core/xoslib/static/vendor/ \
 && cp /tmp/ng-xos-lib/dist/ngXosVendor.min.js /opt/xos/core/xoslib/static/vendor/

RUN chmod +x /opt/xos/tools/xos-manage \
 && sync \
 && /opt/xos/tools/xos-manage genkeys

EXPOSE 8000

# Set environment variables
ENV HOME /root

# Define working directory
WORKDIR /opt/xos

# Define default command
CMD python /opt/xos/manage.py runserver 0.0.0.0:8000 --insecure --makemigrations

